### ISSUE TITLE
sample DOM sink from webworker with rAf from main thread

### ISSUE THREAD

**Issue by aronallen** [aronallen/cycle-sandbox#11]
We still need to optimize performance.
If a window goes to the background, we should stop any DOM updates from being transferred.
By sending an event for each animation frame, and sampling the latest DOM sink event, we should be fine.

**Comment by michalvankodev** [comment]
I think this optimization is out of scope for sandboxing. There might be a lot of use cases where you don't want to stop rendering. e.g. you have a popup window opened in front of the webpage. Webpage would look like its blocked. Cycle-sandbox should be focusing only on one thing - sandboxing components. Everything else should be part of the business logic for the application.

**Comment by aronallen** [comment]
Hi,

Perhaps it should be an option or it should do it at a much lower rate,
with the sample I provided you can see what happens if you go away for a
while and then come back, all the changes are applied, and the queue is
emptied, and the UI stalls until the changes are done, I think we need to
do something about this behavior.
