### ISSUE TITLE
Investigate memory leak in EventDelegator

### ISSUE THREAD

**Issue by aronallen** [aronallen/cycle-sandbox#3]
Perhaps related to many stream adaptions?

**Comment by michalvankodev** [comment]
Needs better investigation. This issue might caused by DOM driver itself.

**Comment by aronallen** [comment]
It is reproducible without @cycle/sandbox, so I filed a bug.

**Comment by aronallen** [comment]
https://github.com/cyclejs/cyclejs/issues/587
